export type AdminRole = 'owner'|'admin'|'operator'|'viewer';
export type AdminScope = 'tenant:read'|'tenant:write'|'wallet:read'|'wallet:write'|'auth:write'|'audit:read'|'migration:write';
const roleScopes: Record<AdminRole, readonly AdminScope[]> = {
  owner:['tenant:read','tenant:write','wallet:read','wallet:write','auth:write','audit:read','migration:write'],
  admin:['tenant:read','tenant:write','wallet:read','wallet:write','auth:write','audit:read'],
  operator:['tenant:read','wallet:read','wallet:write','audit:read'], viewer:['tenant:read','wallet:read','audit:read']
};
export interface AdminPrincipal { readonly tenantId: string; readonly role: AdminRole; readonly scopes?: readonly AdminScope[]; readonly reauthenticated?: boolean; }
export interface MutationPlan { readonly operation: string; readonly chainId: number; readonly target: `0x${string}`; readonly cost: string; readonly simulation: 'passed'|'failed'|'not-run'; readonly policy: 'allowed'|'denied'; readonly dangerous?: boolean; readonly tenantId: string; }
export interface AuditEvent { readonly id: string; readonly tenantId: string; readonly action: string; readonly outcome: 'allowed'|'denied'; readonly actor: string; readonly metadata?: Record<string, string|number|boolean>; }
export class AdminConsoleError extends Error { constructor(readonly code: 'FORBIDDEN'|'TENANT_MISMATCH'|'REAUTH_REQUIRED'|'CONFIRMATION_REQUIRED'|'INVALID_MUTATION'|'SECRET_UNAVAILABLE'|'PROVIDER_ERROR', message: string) { super(message); this.name='AdminConsoleError'; } }
const hasScope = (p: AdminPrincipal, scope: AdminScope) => roleScopes[p.role].includes(scope) && (p.scopes === undefined || p.scopes.includes(scope));
export function authorize(principal: AdminPrincipal, scope: AdminScope, tenantId: string): void { if (principal.tenantId !== tenantId) throw new AdminConsoleError('TENANT_MISMATCH','Tenant boundary violation'); if (!hasScope(principal,scope)) throw new AdminConsoleError('FORBIDDEN','Insufficient administrative scope'); }
export function validateMutation(principal: AdminPrincipal, plan: MutationPlan, scope: AdminScope, confirmed = false): MutationPlan { authorize(principal,scope,plan.tenantId); if (!Number.isSafeInteger(plan.chainId) || plan.chainId < 1 || !/^0x[0-9a-f]{40}$/iu.test(plan.target) || !plan.cost || plan.simulation !== 'passed' || plan.policy !== 'allowed') throw new AdminConsoleError('INVALID_MUTATION','Mutation requires chain, target, cost, successful simulation and policy approval'); if (plan.dangerous && !principal.reauthenticated) throw new AdminConsoleError('REAUTH_REQUIRED','Step-up authentication required'); if (plan.dangerous && !confirmed) throw new AdminConsoleError('CONFIRMATION_REQUIRED','Explicit confirmation required'); return Object.freeze({...plan}); }
export class WriteOnceSecretStore { private readonly records = new Map<string,{secret:string; createdAt:string}>(); create(id: string, secret: string): { id:string; createdAt:string } { if (!id || !secret || this.records.has(id)) throw new AdminConsoleError('SECRET_UNAVAILABLE','Secret cannot be created or replaced'); const createdAt=new Date().toISOString(); this.records.set(id,{secret,createdAt}); return {id,createdAt}; } read(_id: string): never { throw new AdminConsoleError('SECRET_UNAVAILABLE','Secrets are write-only and cannot be read'); } }
export function redactProviderError(error: unknown): AdminConsoleError { const message = error instanceof Error ? error.message : 'provider request failed'; const safe = message.replace(/(api[_-]?key|secret|token|password|authorization)\s*[:=]\s*[^\s,;]+/giu,'$1=[redacted]').slice(0,160); return new AdminConsoleError('PROVIDER_ERROR',`Provider request failed: ${safe}`); }
export function listAudit(principal: AdminPrincipal, events: readonly AuditEvent[], tenantId: string): readonly AuditEvent[] { authorize(principal,'audit:read',tenantId); return events.filter(e=>e.tenantId===tenantId).map(e=>({...e,metadata:e.metadata ? Object.fromEntries(Object.entries(e.metadata).filter(([k])=>!/(secret|token|password|credential|vc|email)/iu.test(k))) : undefined})); }
